---
# tasks file for instalacion
 - name: Instalacion de paquete
   yum:
     name: '{{ paquetes }}'
     state: present
   notify: restart httpd
   when: (ansible_facts['distribution'] == "CentOS")  
...
